//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/03/2012 12:20:22
namespace L24CM.Models
{
    
    /// <summary>
    /// There are no comments for L24CMEntities in the schema.
    /// </summary>
    public partial class L24CMEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new L24CMEntities object using the connection string found in the 'L24CMEntities' section of the application configuration file.
        /// </summary>
        public L24CMEntities() : 
                base("name=L24CMEntities", "L24CMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new L24CMEntities object.
        /// </summary>
        public L24CMEntities(string connectionString) : 
                base(connectionString, "L24CMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new L24CMEntities object.
        /// </summary>
        public L24CMEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "L24CMEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ContentItemSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ContentItem> ContentItemSet
        {
            get
            {
                if ((this._ContentItemSet == null))
                {
                    this._ContentItemSet = base.CreateQuery<ContentItem>("[ContentItemSet]");
                }
                return this._ContentItemSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ContentItem> _ContentItemSet;
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> UserSet
        {
            get
            {
                if ((this._UserSet == null))
                {
                    this._UserSet = base.CreateQuery<User>("[UserSet]");
                }
                return this._UserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _UserSet;
        /// <summary>
        /// There are no comments for ContentItemSet in the schema.
        /// </summary>
        public void AddToContentItemSet(ContentItem contentItem)
        {
            base.AddObject("ContentItemSet", contentItem);
        }
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
    }
    /// <summary>
    /// There are no comments for l24cmModel.ContentItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Path
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="l24cmModel", Name="ContentItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ContentItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ContentItem object.
        /// </summary>
        /// <param name="path">Initial value of Path.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="action">Initial value of Action.</param>
        /// <param name="controller">Initial value of Controller.</param>
        /// <param name="addressKey">Initial value of AddressKey.</param>
        /// <param name="versionKey">Initial value of VersionKey.</param>
        public static ContentItem CreateContentItem(string path, string type, string action, string controller, string addressKey, string versionKey)
        {
            ContentItem contentItem = new ContentItem();
            contentItem.Path = path;
            contentItem.Type = type;
            contentItem.Action = action;
            contentItem.Controller = controller;
            contentItem.AddressKey = addressKey;
            contentItem.VersionKey = versionKey;
            return contentItem;
        }
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this.ReportPropertyChanging("Path");
                this._Path = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Path");
                this.OnPathChanged();
            }
        }
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Action in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this.OnActionChanging(value);
                this.ReportPropertyChanging("Action");
                this._Action = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Action");
                this.OnActionChanged();
            }
        }
        private string _Action;
        partial void OnActionChanging(string value);
        partial void OnActionChanged();
        /// <summary>
        /// There are no comments for Property Controller in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Controller
        {
            get
            {
                return this._Controller;
            }
            set
            {
                this.OnControllerChanging(value);
                this.ReportPropertyChanging("Controller");
                this._Controller = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Controller");
                this.OnControllerChanged();
            }
        }
        private string _Controller;
        partial void OnControllerChanging(string value);
        partial void OnControllerChanged();
        /// <summary>
        /// There are no comments for Property Subindex0 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex0
        {
            get
            {
                return this._Subindex0;
            }
            set
            {
                this.OnSubindex0Changing(value);
                this.ReportPropertyChanging("Subindex0");
                this._Subindex0 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex0");
                this.OnSubindex0Changed();
            }
        }
        private string _Subindex0;
        partial void OnSubindex0Changing(string value);
        partial void OnSubindex0Changed();
        /// <summary>
        /// There are no comments for Property Subindex1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex1
        {
            get
            {
                return this._Subindex1;
            }
            set
            {
                this.OnSubindex1Changing(value);
                this.ReportPropertyChanging("Subindex1");
                this._Subindex1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex1");
                this.OnSubindex1Changed();
            }
        }
        private string _Subindex1;
        partial void OnSubindex1Changing(string value);
        partial void OnSubindex1Changed();
        /// <summary>
        /// There are no comments for Property Subindex2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex2
        {
            get
            {
                return this._Subindex2;
            }
            set
            {
                this.OnSubindex2Changing(value);
                this.ReportPropertyChanging("Subindex2");
                this._Subindex2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex2");
                this.OnSubindex2Changed();
            }
        }
        private string _Subindex2;
        partial void OnSubindex2Changing(string value);
        partial void OnSubindex2Changed();
        /// <summary>
        /// There are no comments for Property Subindex3 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex3
        {
            get
            {
                return this._Subindex3;
            }
            set
            {
                this.OnSubindex3Changing(value);
                this.ReportPropertyChanging("Subindex3");
                this._Subindex3 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex3");
                this.OnSubindex3Changed();
            }
        }
        private string _Subindex3;
        partial void OnSubindex3Changing(string value);
        partial void OnSubindex3Changed();
        /// <summary>
        /// There are no comments for Property Subindex4 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex4
        {
            get
            {
                return this._Subindex4;
            }
            set
            {
                this.OnSubindex4Changing(value);
                this.ReportPropertyChanging("Subindex4");
                this._Subindex4 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex4");
                this.OnSubindex4Changed();
            }
        }
        private string _Subindex4;
        partial void OnSubindex4Changing(string value);
        partial void OnSubindex4Changed();
        /// <summary>
        /// There are no comments for Property Subindex5 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subindex5
        {
            get
            {
                return this._Subindex5;
            }
            set
            {
                this.OnSubindex5Changing(value);
                this.ReportPropertyChanging("Subindex5");
                this._Subindex5 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subindex5");
                this.OnSubindex5Changed();
            }
        }
        private string _Subindex5;
        partial void OnSubindex5Changing(string value);
        partial void OnSubindex5Changed();
        /// <summary>
        /// There are no comments for Property AddressKey in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressKey
        {
            get
            {
                return this._AddressKey;
            }
            set
            {
                this.OnAddressKeyChanging(value);
                this.ReportPropertyChanging("AddressKey");
                this._AddressKey = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AddressKey");
                this.OnAddressKeyChanged();
            }
        }
        private string _AddressKey;
        partial void OnAddressKeyChanging(string value);
        partial void OnAddressKeyChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private global::System.Nullable<int> _Version;
        partial void OnVersionChanging(global::System.Nullable<int> value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property VersionKey in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionKey
        {
            get
            {
                return this._VersionKey;
            }
            set
            {
                this.OnVersionKeyChanging(value);
                this.ReportPropertyChanging("VersionKey");
                this._VersionKey = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VersionKey");
                this.OnVersionKeyChanged();
            }
        }
        private string _VersionKey;
        partial void OnVersionKeyChanging(string value);
        partial void OnVersionKeyChanged();
    }
    /// <summary>
    /// There are no comments for l24cmModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="l24cmModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="modified">Initial value of Modified.</param>
        /// <param name="roles">Initial value of Roles.</param>
        /// <param name="userName">Initial value of UserName.</param>
        public static User CreateUser(global::System.DateTime created, global::System.Guid id, global::System.DateTime modified, string roles, string userName)
        {
            User user = new User();
            user.Created = created;
            user.Id = id;
            user.Modified = modified;
            user.Roles = roles;
            user.UserName = userName;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this.ReportPropertyChanging("Created");
                this._Created = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Created");
                this.OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this.ReportPropertyChanging("Modified");
                this._Modified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Modified");
                this.OnModifiedChanged();
            }
        }
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Roles
        {
            get
            {
                return this._Roles;
            }
            set
            {
                this.OnRolesChanging(value);
                this.ReportPropertyChanging("Roles");
                this._Roles = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Roles");
                this.OnRolesChanged();
            }
        }
        private string _Roles;
        partial void OnRolesChanging(string value);
        partial void OnRolesChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
    }
}
