//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace L24CM.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class L24CMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new L24CMEntities object using the connection string found in the 'L24CMEntities' section of the application configuration file.
        /// </summary>
        public L24CMEntities() : base("name=L24CMEntities", "L24CMEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new L24CMEntities object.
        /// </summary>
        public L24CMEntities(string connectionString) : base(connectionString, "L24CMEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new L24CMEntities object.
        /// </summary>
        public L24CMEntities(EntityConnection connection) : base(connection, "L24CMEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentItem> ContentItemSet
        {
            get
            {
                if ((_ContentItemSet == null))
                {
                    _ContentItemSet = base.CreateObjectSet<ContentItem>("ContentItemSet");
                }
                return _ContentItemSet;
            }
        }
        private ObjectSet<ContentItem> _ContentItemSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> UserSet
        {
            get
            {
                if ((_UserSet == null))
                {
                    _UserSet = base.CreateObjectSet<User>("UserSet");
                }
                return _UserSet;
            }
        }
        private ObjectSet<User> _UserSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentItemSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentItemSet(ContentItem contentItem)
        {
            base.AddObject("ContentItemSet", contentItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="l24cmModel", Name="ContentItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentItem object.
        /// </summary>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="controller">Initial value of the Controller property.</param>
        /// <param name="addressKey">Initial value of the AddressKey property.</param>
        /// <param name="versionKey">Initial value of the VersionKey property.</param>
        public static ContentItem CreateContentItem(global::System.String path, global::System.String type, global::System.String action, global::System.String controller, global::System.String addressKey, global::System.String versionKey)
        {
            ContentItem contentItem = new ContentItem();
            contentItem.Path = path;
            contentItem.Type = type;
            contentItem.Action = action;
            contentItem.Controller = controller;
            contentItem.AddressKey = addressKey;
            contentItem.VersionKey = versionKey;
            return contentItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                if (_Path != value)
                {
                    OnPathChanging(value);
                    ReportPropertyChanging("Path");
                    _Path = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Path");
                    OnPathChanged();
                }
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Controller
        {
            get
            {
                return _Controller;
            }
            set
            {
                OnControllerChanging(value);
                ReportPropertyChanging("Controller");
                _Controller = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Controller");
                OnControllerChanged();
            }
        }
        private global::System.String _Controller;
        partial void OnControllerChanging(global::System.String value);
        partial void OnControllerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex0
        {
            get
            {
                return _Subindex0;
            }
            set
            {
                OnSubindex0Changing(value);
                ReportPropertyChanging("Subindex0");
                _Subindex0 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex0");
                OnSubindex0Changed();
            }
        }
        private global::System.String _Subindex0;
        partial void OnSubindex0Changing(global::System.String value);
        partial void OnSubindex0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex1
        {
            get
            {
                return _Subindex1;
            }
            set
            {
                OnSubindex1Changing(value);
                ReportPropertyChanging("Subindex1");
                _Subindex1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex1");
                OnSubindex1Changed();
            }
        }
        private global::System.String _Subindex1;
        partial void OnSubindex1Changing(global::System.String value);
        partial void OnSubindex1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex2
        {
            get
            {
                return _Subindex2;
            }
            set
            {
                OnSubindex2Changing(value);
                ReportPropertyChanging("Subindex2");
                _Subindex2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex2");
                OnSubindex2Changed();
            }
        }
        private global::System.String _Subindex2;
        partial void OnSubindex2Changing(global::System.String value);
        partial void OnSubindex2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex3
        {
            get
            {
                return _Subindex3;
            }
            set
            {
                OnSubindex3Changing(value);
                ReportPropertyChanging("Subindex3");
                _Subindex3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex3");
                OnSubindex3Changed();
            }
        }
        private global::System.String _Subindex3;
        partial void OnSubindex3Changing(global::System.String value);
        partial void OnSubindex3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex4
        {
            get
            {
                return _Subindex4;
            }
            set
            {
                OnSubindex4Changing(value);
                ReportPropertyChanging("Subindex4");
                _Subindex4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex4");
                OnSubindex4Changed();
            }
        }
        private global::System.String _Subindex4;
        partial void OnSubindex4Changing(global::System.String value);
        partial void OnSubindex4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subindex5
        {
            get
            {
                return _Subindex5;
            }
            set
            {
                OnSubindex5Changing(value);
                ReportPropertyChanging("Subindex5");
                _Subindex5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subindex5");
                OnSubindex5Changed();
            }
        }
        private global::System.String _Subindex5;
        partial void OnSubindex5Changing(global::System.String value);
        partial void OnSubindex5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressKey
        {
            get
            {
                return _AddressKey;
            }
            set
            {
                OnAddressKeyChanging(value);
                ReportPropertyChanging("AddressKey");
                _AddressKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressKey");
                OnAddressKeyChanged();
            }
        }
        private global::System.String _AddressKey;
        partial void OnAddressKeyChanging(global::System.String value);
        partial void OnAddressKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private Nullable<global::System.Int32> _Version;
        partial void OnVersionChanging(Nullable<global::System.Int32> value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VersionKey
        {
            get
            {
                return _VersionKey;
            }
            set
            {
                OnVersionKeyChanging(value);
                ReportPropertyChanging("VersionKey");
                _VersionKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VersionKey");
                OnVersionKeyChanged();
            }
        }
        private global::System.String _VersionKey;
        partial void OnVersionKeyChanging(global::System.String value);
        partial void OnVersionKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="l24cmModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="modified">Initial value of the Modified property.</param>
        /// <param name="roles">Initial value of the Roles property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static User CreateUser(global::System.DateTime created, global::System.Guid id, global::System.DateTime modified, global::System.String roles, global::System.String userName)
        {
            User user = new User();
            user.Created = created;
            user.Id = id;
            user.Modified = modified;
            user.Roles = roles;
            user.UserName = userName;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
    }

    #endregion
    
}
